sudo: false
notifications:
  email: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libopencv-dev
    - xvfb
    - gcc-4.8
    - g++-4.8
before_script:
  # For headless testing of the sample application (cv::imshow)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  # Use newer gcc and g++
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  # Run CMake in order to generate makefile
  - mkdir ../build
  - cd ../build
  - cmake ../itseez-ws-2016-practice
  # Build
  - make
  # Run regression tests
  - ./bin/test_skeleton
  # Run performance tests (we take only one sample, so we don't wait long)
  - ./bin/perf_skeleton --perf_min_samples=1 --perf_force_samples=1 --gtest_output=xml:perf_report.xml
  # Print performance metrics
  - ../itseez-ws-2016-practice/3rdparty/opencv_ptest/misc/summary.py ./perf_report.xml
  # Run sample application
  - ./bin/skeleton --image ./bin/testdata/page.png --save
